version: 2

models:
  - name: fct_job_ads
    columns:
      - name: occupation_id
        tests:
          - relationships:
              to: ref('dim_occupation')
              field: occupation_id
          - not_null
      - name: auxilliary_id
        tests: 
          - relationships:
              to: ref('dim_auxilliary_attributes')
              field: auxilliary_id 
          - not_null
      - name: employer_id
        tests: 
          - relationships:
              to: ref('dim_employer')
              field: employer_id
          - not_null
      - name: job_details_id
        tests: 
          - relationships:
              to: ref('dim_job_details')
              field: job_details_id
          - not_null
      - name: job_description_id
        tests: 
          - relationships:
              to: ref('dim_job_description')
              field: job_description_id
          - not_null
          - unique
        

      - name: relevance
        tests:
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float

      - name: vacancies
        tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 1
              max_value: 20
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 1
              max_value: 20
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
      - name: application_deadline
        tests: 
          - not_null
        

  - name: dim_employer
    columns:
      - name : employer_id
        tests:
          - not_null
          - unique
      - name: employer_name
        description: "The name of the employer (grouping key)."
        tests:
          - not_null
      - name : employer_workplace
        tests:
          - not_null
      - name : workplace_street_address
        tests:
          - not_null
      - name : workplace_region
        tests:
          - not_null
      - name : workplace_postcode
        tests:
          - not_null
      - name : workplace_city
        tests:
          - not_null
      - name : workplace_country
        tests:
          - not_null
      - name : employer_organization_number
        tests:
          - not_null




  - name: dim_occupation
    columns:
      - name: occupation_id
        description: "Surrogate key generated from occupation."
        tests:
          - not_null
          - unique


      - name: occupation
        description: "Occupation name (grouping key)."
        tests:
          - not_null
          - unique
 
      - name: occupation_group
        tests:
          - not_null
      - name: occupation_field
        tests:
          - not_null

  - name: dim_auxilliary_attributes
    columns:
      - name: auxilliary_id
        tests:
          - not_null
          - unique
      - name: experience_required
        tests:
          - not_null
      - name: access_to_own_car
        tests:
          - not_null
      - name: driving_license_required
        tests:
          - not_null


  - name: dim_job_description 
    columns:
      - name: job_description_id
        tests:
          - not_null
          - unique
      - name: headline
        tests:
          - not_null
      - name: description_text
        tests:
          - not_null
      - name: description_html
        tests:
          - not_null

  - name: dim_job_details
    columns:
      - name: job_details_id
        tests:
          - not_null
          - unique
      - name: employment_type
        tests:
          - not_null
      - name: salary_type
        tests:
          - not_null
      - name: duration
        tests:
          - not_null
      - name: scope_of_work_max
        tests:
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 0
              max_value: 100
              config:
                severity: warn   
      - name: scope_of_work_min
        tests:
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 0
              max_value: 100
              config:
                severity: warn


